debug: True
log:
  level: DEBUG


entryPoints:
  web-entry:
    address: :80
#    redirections:
#      entryPoint:
#        to: web-entry-secure
#        scheme: https
  web-entry-secure:
    address: :443


api:
  dashboard: true
  insecure: true


providers:
  docker:
    exposedByDefault: false
    swarmMode: true
